language: node_js
node_js:
  - "10"
script:
  - echo "Deploy!!"
install:
  - npm install
  - npm install -g firebase-tools
after_success:
  - ng build --prod=true --aot=true
  - firebase deploy --project cv-page-application --token $FIREBASE_TOKEN
