language: node_js
node_js:
  - "10"
script:
  - echo "Deploy!!"
install:
  - npm install
after_success:
  - ng build --prod --aot
  - firebase deploy --project cv-page-application --token $FIREBASE_TOKEN
