language: node_js
node_js:
  - "7"
script:
  - echo "Deploy!!"
install:
  - npm install -g @angular/cli
  - npm install -g firebase-tools
after_success:
  - ng build --prod --aot
  - firebase deploy --project cv-page-application --token $FIREBASE_TOKEN
